import { expect, test } from '@playwright/test'
import { authenticate, mockHermesApi, TEST_ACCESS_KEY } from './fixtures'

for (const mobile of [false, true]) test(`DSH native slot and plugin list retain their state (${mobile ? 'mobile' : 'desktop'})`, async ({ page }) => {
  if (mobile) await page.setViewportSize({ width: 390, height: 844 })
  await authenticate(page, TEST_ACCESS_KEY, 'research')
  await page.addInitScript(() => localStorage.setItem('hermes_brightness', 'system'))
  await page.emulateMedia({ colorScheme: 'dark' })
  const api = await mockHermesApi(page)
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  let opens = 0
  await page.route('**/api/coding-agents/dsh/ui-session', route => { opens++; return route.fulfill({ json: { id: 'fixture', path: '/api/coding-agents/dsh/ui/fixture/' } }) })
  await page.route('**/api/coding-agents/dsh/ui-session/fixture', route => route.fulfill({ status: 204 }))
  await page.route('**/api/coding-agents/dsh/ui/fixture/**', route => route.fulfill({ contentType: 'text/html', body: '<!doctype html><label>Plugin-owned field<input></label><script>document.body.dataset.theme=new URL(location.href).searchParams.get("studioTheme");window.addEventListener("message",e=>{if(e.data?.type==="studio-dsh-theme")document.body.dataset.theme=e.data.theme});parent.postMessage({type:"studio-dsh-ui-ready"},location.origin)</script>' }))
  const inventory: any = { source: 'native-presets', sourceHome: '/fixture/.dsh', packageVersion: '0.1.5-rc.2', defaultPreset: 'standard', runtimeConnected: false, discovery: 'shipped-and-user-roots',
    web: { profile: 'web', revision: 'a'.repeat(64), sourcePath: '/fixture/.dsh/profiles/web/package.json', packages: [{ name: '@liustack/modlens', title: 'ModLens', description: 'Vision tools for text-only models.', version: '3.26.1', requested: 'github:liustack/modlens#a1923d0', bundle: true, containsBrowserPart: true, error: '' }] },
    presets: [{ id: 'standard', name: 'Standard', isDefault: true, trust: 'system', sourcePath: '/fixture/standard/agent.cordis.yml', entries: Array.from({ length: 28 }, (_, i) => ({ entryId: `tool-${i}`, moduleName: `@deepseek-ai/tool-${i}`, configuredEnabled: true, runtimePhase: null, groupPath: [] })) }] }
  await page.route('**/api/coding-agents/dsh/plugin-inventory', route => route.fulfill({ json: inventory }))
  await page.route('**/api/coding-agents/dsh/web-plugins', route => {
    expect(route.request().headers()['if-match']).toBe(`"${inventory.web.revision}"`)
    expect(route.request().postDataJSON()).toEqual({ action: 'remove', packageName: '@liustack/modlens' })
    inventory.web.packages = []; return route.fulfill({ json: inventory })
  })
  await page.goto('/#/studio/agents/dsh/plugins')
  const panel = page.getByTestId('dsh-plugins')
  await expect(panel.getByRole('tab')).toHaveCount(2)
  const input = panel.frameLocator('iframe').getByLabel('Plugin-owned field')
  await input.fill('native draft')
  const nativeBody = panel.frameLocator('iframe').locator('body')
  await expect(nativeBody).toHaveAttribute('data-theme', 'dark')
  await page.emulateMedia({ colorScheme: 'light' })
  await expect(nativeBody).toHaveAttribute('data-theme', 'light')
  await page.emulateMedia({ colorScheme: 'dark' })
  await expect(nativeBody).toHaveAttribute('data-theme', 'dark')
  await expect(input).toHaveValue('native draft')
  expect(opens).toBe(1)
  await panel.getByRole('tab', { name: 'Plugin list', exact: true }).click()
  await expect(panel.getByTestId('dsh-web-package')).toContainText('ModLens')
  await expect(panel.getByTestId('dsh-web-package')).toContainText('Vision tools for text-only models.')
  await expect(panel.getByTestId('native-plugin-count')).toHaveText('28')
  await expect(page.getByTestId('managed-packages')).toHaveCount(0)
  await panel.getByRole('tab', { name: 'Plugin configuration', exact: true }).click()
  await expect(input).toHaveValue('native draft'); expect(opens).toBe(1)
  await panel.getByRole('tab', { name: 'Plugin list', exact: true }).click()
  await panel.getByTestId('dsh-web-package').getByRole('button', { name: 'Remove' }).click()
  await page.locator('.n-popconfirm').getByRole('button', { name: 'Confirm', exact: true }).click()
  await expect(panel.getByTestId('dsh-web-package')).toHaveCount(0)
  await panel.getByRole('tab', { name: 'Plugin configuration', exact: true }).click()
  await expect.poll(() => opens).toBe(2)
  expect(api.unexpectedRequests).toEqual([]); expect(errors).toEqual([])
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

for (const mobile of [false, true]) test(`DSH Agent presets use Studio components (${mobile ? 'mobile' : 'desktop'})`, async ({ page }) => {
  if (mobile) await page.setViewportSize({ width: 390, height: 844 })
  await authenticate(page, TEST_ACCESS_KEY, 'research')
  const api = await mockHermesApi(page)
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  const roster = { authorable: true, presets: [{ id: 'standard', name: 'Standard mode', description: 'File editing, shell and web search.', trust: 'system', isDefault: true }] }
  await page.route('**/api/coding-agents/dsh/agent-presets**', async route => {
    const req = route.request(), path = new URL(req.url()).pathname
    if (req.method() === 'POST') {
      expect(req.postDataJSON()).toEqual({ from: 'standard', id: 'my-agent', name: 'My Agent' })
      roster.presets.push({ id: 'my-agent', name: 'My Agent', description: roster.presets[0].description, trust: 'user', isDefault: false })
    } else if (req.method() === 'PUT') {
      expect(path.endsWith('/my-agent/default')).toBe(true)
      roster.presets.forEach(row => { row.isDefault = row.id === 'my-agent' })
    } else if (req.method() === 'DELETE') {
      expect(path.endsWith('/my-agent')).toBe(true)
      roster.presets = roster.presets.filter(row => row.id !== 'my-agent')
    } else if (path.endsWith('/standard')) return route.fulfill({ json: { agentPreset: 'standard', content: '- name: native-tool' } })
    return route.fulfill({ json: roster })
  })
  await page.goto('/#/studio/agents/dsh/presets')
  const panel = page.getByTestId('dsh-agent-presets')
  await expect(panel.getByRole('heading', { name: 'Agent presets', exact: true })).toBeVisible()
  await expect(panel.locator('iframe')).toHaveCount(0)
  await expect(page.getByTestId('coding-agent-config-presets')).toHaveCount(1)
  const standard = panel.getByTestId('dsh-preset-standard')
  await expect(standard).toContainText('File editing, shell and web search.')
  await expect(standard.getByRole('button', { name: 'Delete', exact: true })).toHaveCount(0)
  await standard.getByRole('button', { name: 'View', exact: true }).click()
  await expect(page.locator('.preset-viewer')).toContainText('- name: native-tool')
  await page.keyboard.press('Escape')
  await standard.getByRole('button', { name: 'Duplicate', exact: true }).click()
  await page.getByRole('textbox', { name: 'Identifier', exact: true }).fill('standard')
  await expect(page.getByRole('button', { name: 'Create', exact: true })).toBeDisabled()
  await page.getByRole('textbox', { name: 'Identifier', exact: true }).fill('my-agent')
  await page.getByRole('textbox', { name: 'Name', exact: true }).fill('My Agent')
  await page.getByRole('button', { name: 'Create', exact: true }).click()
  const custom = panel.getByTestId('dsh-preset-my-agent')
  await expect(custom).toBeVisible()
  await custom.getByRole('button', { name: 'Set as default', exact: true }).click()
  await expect(custom.getByRole('button', { name: 'Set as default', exact: true })).toBeDisabled()
  await expect(custom.locator('.n-tag').filter({ hasText: /^Default$/ })).toBeVisible()
  await page.screenshot({ path: `/tmp/dsh-presets-studio-${mobile ? 'mobile' : 'desktop'}.png` })
  await custom.getByRole('button', { name: 'Delete', exact: true }).click()
  await page.locator('.n-popconfirm').getByRole('button', { name: 'Confirm', exact: true }).click()
  await expect(custom).toHaveCount(0)
  await page.goto('/#/studio/agents/codex/presets')
  await expect(page).toHaveURL(/\/studio\/agents\/codex\/settings/)
  await expect(page.getByTestId('coding-agent-config-presets')).toHaveCount(0)
  expect(api.unexpectedRequests).toEqual([]); expect(errors).toEqual([])
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
