import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

describe('Agent Manager routing', () => {
  it('is the only Agent management page and preserves the old URL as a redirect', () => {
    const sidebar = readFileSync('packages/client/src/components/layout/PageSidebarNav.vue', 'utf8')
    const appSidebar = readFileSync('packages/client/src/components/layout/AppSidebar.vue', 'utf8')
    const chatPanel = readFileSync('packages/client/src/components/hermes/chat/ChatPanel.vue', 'utf8')
    const chatView = readFileSync('packages/client/src/views/hermes/ChatView.vue', 'utf8')
    const manager = readFileSync('packages/client/src/views/hermes/AgentManagerView.vue', 'utf8')
    const router = readFileSync('packages/client/src/router/index.ts', 'utf8')

    expect(sidebar.indexOf("t('sidebar.agentManager')"))
      .toBeGreaterThan(sidebar.indexOf("t('sidebar.connections')"))
    expect(sidebar.indexOf("t('sidebar.models')"))
      .toBeGreaterThan(sidebar.indexOf("t('sidebar.agentManager')"))
    const routeStart = router.indexOf("path: '/studio/agents'")
    const route = router.slice(routeStart, router.indexOf("path: '/hermes/group-chat'", routeStart))
    expect(route).toContain("path: '/studio/agents'")
    expect(route).toContain("name: 'hermes.agentManager'")
    expect(route).toContain("component: () => import('@/views/hermes/ChatView.vue')")
    expect(route).toContain('requiresSuperAdmin: true')
    expect(route).toContain("path: '/hermes/agents'")
    expect(route).toContain("redirect: { name: 'hermes.agentManager' }")
    expect(router).toContain("path: '/hermes/coding-agents'")
    expect(router).toContain("redirect: { name: 'hermes.agentManager' }")
    expect(router).not.toContain('CodingAgentsView.vue')
    expect(appSidebar).not.toContain("hermes.codingAgents")
    expect(appSidebar).not.toContain("hermes.models")
    expect(manager).not.toContain("hermes.codingAgents")
    expect(manager).not.toContain("agentManager.configure")
    expect(manager).not.toContain('PageSidebarNav')
    expect(manager).not.toContain('sidebar-summary')
    expect(chatView).toContain("if (route.name === 'hermes.agentManager') return 'agents'")
    expect(chatView).toContain("if (route.name === 'hermes.models') return 'models'")
    expect(chatPanel).toContain('contentMode?: "chat" | "connections" | "agents" | "models";')
    expect(chatPanel).toContain("const AgentManagerPanel = defineAsyncComponent")
    expect(chatPanel).toContain("contentMode === 'agents' ? 'agents'")
    expect(chatPanel).toContain('v-else-if="contentMode === \'agents\'"')
    expect(chatPanel).toContain('v-else-if="contentMode === \'models\'"')
    expect(chatPanel).toContain('fetchAgentAvailabilitySnapshot()')
    expect(chatPanel).toContain('agentInstallationState(status, "hermes") === "not-installed"')
    expect(chatPanel).not.toContain('fetchRuntimeVersionStatus({ probeRuntime: false')
    expect(chatPanel).toContain('router.push({ name: "hermes.agentManager", query: { runtime: "install" } })')
  })
})
