import { readFileSync } from 'fs'
import { describe, expect, it } from 'vitest'

const source = readFileSync(
  'packages/client/src/components/hermes/connections/AppConnectionsPanel.vue',
  'utf8',
)
const controllerSource = readFileSync(
  'packages/server/src/modules/studio/controllers/app-connections.ts',
  'utf8',
)

describe('App connections scan modal', () => {
  it('switches between the connection list, mobile download hub, and message push', () => {
    expect(source).toContain("type AppPanelView = 'list' | 'download' | 'messages'")
    expect(source).toContain('normalizePanelView(route.query.view)')
    expect(source).toContain("t('connections.app.viewList')")
    expect(source).toContain("t('connections.app.viewDownload')")
    expect(source).toContain("t('connections.app.viewMessages')")
    expect(source).toContain("panelView === 'list'")
    expect(source).toContain("updatePanelView('messages')")
    expect(source).toContain('<SocialMessagesView v-else embedded')
    expect(source).toContain('HStudio Mobile')
    expect(source).toContain("const downloadSource = ref<'github' | 'cloudflare'>('cloudflare')")
    expect(source).toContain('fetchStudioVersionManifest()')
    expect(source).toContain('QRCode.toDataURL(requestedUrl')
    expect(source).toContain('class="download-tag-qr"')
    expect(source).toContain('<div v-if="androidDownloadUrl" class="download-tag-qr">')
    expect(source).toContain('<div v-if="googlePlayDownloadUrl" class="download-tag-qr">')
    expect(source).toContain('<div v-if="appleDownloadUrl" class="download-tag-qr">')
    expect(source).toContain('<div v-if="harmonyDownloadUrl" class="download-tag-qr">')
    expect(source).toContain('downloadQrCodeDataUrls.googlePlay')
    expect(source).toContain('downloadQrCodeDataUrls.apple')
    expect(source).toContain('downloadQrCodeDataUrls.harmony')
    expect(source).toContain("t('connections.app.testVersion')")
    expect(source).toContain('class="download-test-status"')
    expect(source).toContain('&:only-child')
    expect(source).toContain('grid-column: 1 / -1')
    expect(source).not.toContain('<NPopover')
    expect(source).toContain('position: absolute')
    expect(source).toContain('width: 112px')
    expect(source).not.toContain('class="app-download-qr-panel"')
    expect(source).toContain('releases/download/v1.0.0/HStudio.apk')
    expect(source).toContain('https://download.ekkolearnai.com/v1.0.0/HStudio.apk')
    expect(source).toContain(':href="androidDownloadUrl"')
    expect(source).toContain('aria-label="GitHub / Cloudflare"')
    expect(source).toContain("t('connections.app.downloadApk')")
    expect(source).toContain('data-platform-icon="google-play"')
    expect(source).toContain('<h4>Android APK</h4>')
    expect(source).toContain('<h4>Android APK</h4>\n              <p>Android</p>')
    expect(source).toContain('<h4>Google Play</h4>')
    expect(source).toContain('<h4>Apple</h4>')
    expect(source).toContain('<h4>HarmonyOS</h4>')
    expect(source.match(/class="app-platform-card(?:\s|\")/g)).toHaveLength(4)
    expect(source).toContain('mobileRelease.channels.apple.testFlightUrl')
    expect(source).toContain('mobileRelease.channels.apple.appStoreUrl')
    expect(source).toContain('appleUsesOfficialRelease')
    expect(source).toContain(':type="appleUsesOfficialRelease ? \'default\' : \'primary\'"')
    expect(source).toContain('max-width: 1180px')
    expect(source).toContain('grid-template-columns: repeat(4, minmax(0, 1fr))')
    expect(source).toContain("t('connections.app.notReleased')")
  })

  it('offers LAN and cloud QR modes with manual refresh and an expired overlay', () => {
    expect(source).toContain('@click="openScanModal"')
    expect(source).toContain('<NTabPane name="lan"')
    expect(source).toContain('<NTabPane name="cloud"')
    expect(source).toContain('QRCode.toDataURL(response.qr_payload')
    expect(source).toContain("t('connections.app.remainingTime', { time: remainingTime })")
    expect(source).toContain("t('connections.app.refreshQr')")
    expect(source).toContain('authorizationLoading.lan && !lanAuthorization')
    expect(source).toContain("authorizationLoading.cloud && !cloudAuthorization")
    expect(source).toContain("const authorizationLoading = ref<Record<'lan' | 'cloud', boolean>>")
    expect(source).toContain('authorization.expires_at <= now')
    expect(source).toContain("ensureCurrentAuthorization('lan')")
    expect(source).toContain("ensureCurrentAuthorization(type, type === 'cloud')")
    expect(source).toContain("cloudAuthorization.value = null")
    expect(source).toContain('class="connection-meta"')
    expect(source).toContain('CONNECTION_POLL_INTERVAL_MS = 3_000')
    expect(source).toContain("document.visibilityState === 'hidden'")
    expect(source).toContain('detectScanConnection: true')
    expect(source).toContain("t('connections.app.connectionDetected')")
    expect(source).toContain("t('connections.app.connectionStatus')")
    expect(source).toContain("t('connections.app.authorizationStatus')")
    expect(source).toContain('deleteAppConnection(connection.id)')
    expect(source).toContain('<NDataTable')
    expect(source).toContain('<NAlert')
    expect(source).toContain('@close="dismissAccessFailure"')
    expect(source).toContain('DISMISSED_ACCESS_FAILURE_KEY')
    expect(source).toContain('nextFailure.occurredAt > dismissedAccessFailureAt.value')
    expect(source).toContain('accessFailureReason')
    expect(source).toContain("failure.plan === 'internal' || failure.plan === 'public_beta'")
    expect(source).toContain("failure.plan === 'paid' && failure.code === 'app_entitlement_expired'")
    expect(source).toContain('failure.tokenTtlSeconds === 0')
    expect(source).toContain('accessFailureMode')
    expect(source).toContain("t('connections.app.accessFailures.tokenExpired')")
    expect(source).toContain("t('connections.app.accessFailures.paidAccountRequired')")
    expect(source).toContain('createCloudAppAuthorization(refresh, cloudRelayRoute.value)')
    expect(source).toContain('updateAppRelayRoute(route)')
    expect(source).toContain("label: 'connections.app.officialRoute'")
    expect(source).toContain("label: 'connections.app.cloudflareRoute'")
    expect(source).not.toContain('option.host')
    expect(source).toContain("generateAuthorization('cloud', true)")
    expect(source).toContain("'connection-qr--expired': authorizationExpired")
    expect(source).toContain('style="width: 560px; max-width: calc(100vw - 32px)"')
    expect(source).not.toContain("t('connections.app.authorizationCode')")
    expect(source).not.toContain('<NInput')
    expect(source).not.toContain('authorization.expires_at <= currentTimestamp.value')
  })

  it('keeps the Studio route in the QR payload as metadata', () => {
    expect(controllerSource).toContain('relay_route: relayRoute')
    expect(controllerSource).toContain('r: relayRoute')
  })
})
