import type { VoiceApiPreset } from '@/types/voice-api'
import { DOUBAO_TTS_2_RESOURCE_ID } from './doubaoTtsVoices'

export const VOICE_API_PRESETS: VoiceApiPreset[] = [
  // TTS Presets
  {
    id: 'tts-edge',
    kind: 'tts',
    provider: 'edge',
    label: 'Edge TTS',
    labelKey: 'settings.voice.presetEdgeTtsLabel',
    description: 'Free high-quality cloud voices from Microsoft Edge.',
    descriptionKey: 'settings.voice.presetEdgeTtsDescription',
    isBuiltin: true,
    isSecretRequired: false,
    capabilities: {
      voices: true,
      rate: true,
      pitch: true,
    },
  },
  {
    id: 'tts-openai',
    kind: 'tts',
    provider: 'openai',
    label: 'OpenAI TTS',
    labelKey: 'settings.voice.presetOpenaiTtsLabel',
    baseUrl: 'https://api.openai.com/v1/audio/speech',
    defaultModel: 'tts-1',
    isSecretRequired: true,
    capabilities: {
      models: true,
      voices: true,
    },
  },
  {
    id: 'tts-elevenlabs',
    kind: 'tts',
    provider: 'elevenlabs',
    label: 'ElevenLabs TTS',
    labelKey: 'settings.voice.presetElevenLabsTtsLabel',
    baseUrl: 'https://api.elevenlabs.io/v1',
    defaultModel: 'eleven_multilingual_v2',
    defaultVoice: 'pNInz6obpgDQGcFmaJgB',
    isSecretRequired: true,
    capabilities: {
      models: true,
      voices: true,
    },
  },
  {
    id: 'tts-gemini',
    kind: 'tts',
    provider: 'gemini',
    label: 'Gemini TTS',
    labelKey: 'settings.voice.presetGeminiTtsLabel',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    defaultModel: 'gemini-2.5-flash-preview-tts',
    defaultVoice: 'Kore',
    isSecretRequired: true,
    capabilities: {
      models: true,
      voices: true,
    },
  },
  {
    id: 'tts-xai',
    kind: 'tts',
    provider: 'xai',
    label: 'xAI TTS',
    labelKey: 'settings.voice.presetXaiTtsLabel',
    baseUrl: 'https://api.x.ai/v1',
    defaultVoice: 'eve',
    isSecretRequired: true,
    capabilities: {
      voices: true,
      language: true,
      speed: true,
      sampleRate: true,
      bitRate: true,
    },
  },
  {
    id: 'tts-mistral',
    kind: 'tts',
    provider: 'mistral',
    label: 'Mistral TTS',
    labelKey: 'settings.voice.presetMistralTtsLabel',
    baseUrl: 'https://api.mistral.ai/v1',
    defaultModel: 'voxtral-mini-tts-2603',
    defaultVoice: 'c69964a6-ab8b-4f8a-9465-ec0925096ec8',
    compatibility: 'openai-compatible',
    isSecretRequired: true,
    capabilities: {
      models: true,
      voices: true,
    },
  },
  {
    id: 'tts-minimax',
    kind: 'tts',
    provider: 'minimax',
    label: 'MiniMax TTS',
    labelKey: 'settings.voice.presetMinimaxTtsLabel',
    baseUrl: 'https://api.minimax.io/v1/t2a_v2',
    defaultModel: 'speech-02-hd',
    defaultVoice: 'English_expressive_narrator',
    isSecretRequired: true,
    capabilities: {
      models: true,
      voices: true,
      speed: true,
      sampleRate: true,
      bitRate: true,
      groupId: true,
      volume: true,
      emotion: true,
    },
  },
  {
    id: 'tts-deepinfra',
    kind: 'tts',
    provider: 'deepinfra',
    label: 'DeepInfra TTS',
    labelKey: 'settings.voice.presetDeepInfraTtsLabel',
    baseUrl: 'https://api.deepinfra.com/v1/openai',
    defaultVoice: 'default',
    compatibility: 'openai-compatible',
    isSecretRequired: true,
    capabilities: {
      models: true,
      voices: true,
      speed: true,
    },
  },
  {
    id: 'tts-mimo',
    kind: 'tts',
    provider: 'mimo',
    label: 'MiMo TTS',
    labelKey: 'settings.voice.presetMimoTtsLabel',
    baseUrl: 'https://api.xiaomimimo.com/v1',
    defaultModel: 'mimo-v2.5-tts',
    isSecretRequired: true,
    capabilities: {
      models: true,
      voices: true,
      stylePrompt: true,
      voiceDesign: true,
      voiceClone: true,
    },
  },
  {
    id: 'tts-doubao',
    kind: 'tts',
    provider: 'doubao',
    label: 'Volcengine Doubao TTS',
    labelKey: 'settings.voice.presetDoubaoTtsLabel',
    baseUrl: 'https://openspeech.bytedance.com/api/v3/tts/unidirectional',
    defaultModel: DOUBAO_TTS_2_RESOURCE_ID,
    isSecretRequired: true,
    capabilities: {
      models: true,
      voices: true,
      stylePrompt: true,
      speed: true,
    },
  },
  {
    id: 'tts-custom',
    kind: 'tts',
    provider: 'custom',
    label: 'Custom TTS',
    labelKey: 'settings.voice.presetCustomTtsLabel',
    isSecretRequired: true,
    capabilities: {
      models: true,
      voices: true,
    },
  },

  // STT Presets
  {
    id: 'stt-local',
    kind: 'stt',
    provider: 'local',
    label: 'Local STT',
    labelKey: 'settings.voice.localSttModelTitle',
    description: 'On-device Chinese-English speech recognition.',
    descriptionKey: 'settings.voice.localSttModelDescription',
    defaultModel: 'sherpa-onnx-streaming-zipformer-bilingual-zh-en-int8-2023-02-20',
    isBuiltin: true,
    isSecretRequired: false,
    capabilities: {},
  },
  {
    id: 'stt-browser',
    kind: 'stt',
    provider: 'browser',
    label: 'Browser STT',
    labelKey: 'settings.voice.presetBrowserSttLabel',
    description: 'Native browser speech recognition API.',
    descriptionKey: 'settings.voice.presetBrowserSttDescription',
    isBuiltin: true,
    isSecretRequired: false,
    capabilities: {},
  },
  {
    id: 'stt-openai',
    kind: 'stt',
    provider: 'openai',
    label: 'OpenAI Whisper',
    labelKey: 'settings.voice.presetOpenaiWhisperLabel',
    baseUrl: 'https://api.openai.com/v1',
    defaultModel: 'whisper-1',
    isSecretRequired: true,
    capabilities: {
      models: true,
    },
  },
  {
    id: 'stt-groq',
    kind: 'stt',
    provider: 'groq',
    label: 'Groq STT',
    labelKey: 'settings.voice.presetGroqSttLabel',
    baseUrl: 'https://api.groq.com/openai/v1',
    defaultModel: 'whisper-large-v3',
    compatibility: 'openai-compatible',
    isSecretRequired: true,
    capabilities: {
      models: true,
    },
  },
  {
    id: 'stt-mistral',
    kind: 'stt',
    provider: 'mistral',
    label: 'Mistral STT',
    labelKey: 'settings.voice.presetMistralSttLabel',
    baseUrl: 'https://api.mistral.ai/v1',
    defaultModel: 'voxtral-mini-latest',
    compatibility: 'openai-compatible',
    isSecretRequired: true,
    capabilities: {
      models: true,
      language: true,
      diarize: true,
    },
  },
  {
    id: 'stt-xai',
    kind: 'stt',
    provider: 'xai',
    label: 'xAI STT',
    labelKey: 'settings.voice.presetXaiSttLabel',
    baseUrl: 'https://api.x.ai/v1',
    isSecretRequired: true,
    capabilities: {
      language: true,
      diarize: true,
      format: true,
    },
  },
  {
    id: 'stt-elevenlabs',
    kind: 'stt',
    provider: 'elevenlabs',
    label: 'ElevenLabs STT',
    labelKey: 'settings.voice.presetElevenLabsSttLabel',
    baseUrl: 'https://api.elevenlabs.io/v1',
    defaultModel: 'scribe_v2',
    isSecretRequired: true,
    capabilities: {
      models: true,
      language: true,
      diarize: true,
      tagAudioEvents: true,
    },
  },
  {
    id: 'stt-deepinfra',
    kind: 'stt',
    provider: 'deepinfra',
    label: 'DeepInfra STT',
    labelKey: 'settings.voice.presetDeepInfraSttLabel',
    baseUrl: 'https://api.deepinfra.com/v1/openai',
    defaultModel: 'openai/whisper-large-v3',
    compatibility: 'openai-compatible',
    isSecretRequired: true,
    capabilities: {
      models: true,
      language: true,
    },
  },
  {
    id: 'stt-doubao',
    kind: 'stt',
    provider: 'doubao',
    label: 'Volcengine Doubao STT',
    labelKey: 'settings.voice.presetDoubaoSttLabel',
    baseUrl: 'https://openspeech.bytedance.com/api/v3/auc/bigmodel',
    defaultModel: 'volc.seedasr.auc',
    isSecretRequired: true,
    capabilities: {
      models: true,
    },
  },
  {
    id: 'stt-custom',
    kind: 'stt',
    provider: 'custom',
    label: 'Custom STT',
    labelKey: 'settings.voice.presetCustomSttLabel',
    isSecretRequired: true,
    capabilities: {
      models: true,
    },
  },
]
