import { randomUUID } from 'crypto'
import { getDb, jsonDelete, jsonGet, jsonGetAll, jsonSet } from '../infrastructure/database'
import { WORKFLOW_SCHEDULE_EVENTS_TABLE, WORKFLOW_SCHEDULES_TABLE, WORKFLOW_SCHEDULE_TRIGGERS_TABLE } from '../infrastructure/database/schemas'

export type WorkflowScheduleEventKind = 'triggered' | 'skipped' | 'failed'
export interface WorkflowScheduleRecord {
  id: string; workflow_id: string; profile: string; owner_user_id: number | null; schedule: string; timezone: string; enabled: boolean
  input: string | null; start_node_ids: string[]; timeout_ms: number | null
  concurrency_policy: 'skip'; misfire_policy: 'skip'; last_scheduled_at: number | null; next_run_at: number | null; last_run_id: string | null; last_error: string | null
  created_at: number; updated_at: number
}
export interface WorkflowScheduleEventRecord { id: string; schedule_id: string; workflow_id: string; trigger_identity: string; scheduled_at: number; kind: WorkflowScheduleEventKind; run_id: string | null; error: string | null; created_at: number }

function array(value: unknown): string[] { try { const parsed = typeof value === 'string' ? JSON.parse(value) : value; return Array.isArray(parsed) ? parsed.map(String) : [] } catch { return [] } }
function row(row: any): WorkflowScheduleRecord { return { id: String(row.id), workflow_id: String(row.workflow_id), profile: String(row.profile || 'default'), owner_user_id: row.owner_user_id == null ? null : Number(row.owner_user_id), schedule: String(row.schedule), timezone: String(row.timezone || 'UTC'), enabled: Boolean(row.enabled), input: row.input == null ? null : String(row.input), start_node_ids: array(row.start_node_ids_json ?? row.start_node_ids), timeout_ms: row.timeout_ms == null ? null : Number(row.timeout_ms), concurrency_policy: 'skip', misfire_policy: 'skip', last_scheduled_at: row.last_scheduled_at == null ? null : Number(row.last_scheduled_at), next_run_at: row.next_run_at == null ? null : Number(row.next_run_at), last_run_id: row.last_run_id == null ? null : String(row.last_run_id), last_error: row.last_error == null ? null : String(row.last_error), created_at: Number(row.created_at), updated_at: Number(row.updated_at) } }
function dbRow(value: WorkflowScheduleRecord): any { return { ...value, enabled: value.enabled ? 1 : 0, start_node_ids_json: JSON.stringify(value.start_node_ids) } }
export function listWorkflowSchedules(workflowId?: string): WorkflowScheduleRecord[] { const db = getDb(); const values = db ? (workflowId ? db.prepare(`SELECT * FROM ${WORKFLOW_SCHEDULES_TABLE} WHERE workflow_id = ? ORDER BY created_at`).all(workflowId) : db.prepare(`SELECT * FROM ${WORKFLOW_SCHEDULES_TABLE} ORDER BY created_at`).all()) as any[] : Object.values(jsonGetAll(WORKFLOW_SCHEDULES_TABLE)).filter((v:any) => !workflowId || v.workflow_id === workflowId); return values.map(row) }
export function getWorkflowSchedule(id: string): WorkflowScheduleRecord | null { const db=getDb(); const value=db ? db.prepare(`SELECT * FROM ${WORKFLOW_SCHEDULES_TABLE} WHERE id = ?`).get(id) : jsonGet(WORKFLOW_SCHEDULES_TABLE,id); return value ? row(value) : null }
export function createWorkflowSchedule(input: Partial<WorkflowScheduleRecord> & Pick<WorkflowScheduleRecord,'workflow_id'|'profile'|'schedule'|'timezone'>): WorkflowScheduleRecord { const now=Date.now(); const value:WorkflowScheduleRecord={id:input.id?.trim()||randomUUID(),workflow_id:input.workflow_id,profile:input.profile||'default',owner_user_id:input.owner_user_id??null,schedule:input.schedule,timezone:input.timezone,enabled:input.enabled!==false,input:input.input??null,start_node_ids:input.start_node_ids||[],timeout_ms:input.timeout_ms??null,concurrency_policy:'skip',misfire_policy:'skip',last_scheduled_at:input.last_scheduled_at??null,next_run_at:input.next_run_at??null,last_run_id:null,last_error:null,created_at:now,updated_at:now}; const db=getDb(); if(db) db.prepare(`INSERT INTO ${WORKFLOW_SCHEDULES_TABLE} (id,workflow_id,profile,owner_user_id,schedule,timezone,enabled,input,start_node_ids_json,timeout_ms,concurrency_policy,misfire_policy,last_scheduled_at,next_run_at,last_run_id,last_error,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(value.id,value.workflow_id,value.profile,value.owner_user_id,value.schedule,value.timezone,value.enabled?1:0,value.input,JSON.stringify(value.start_node_ids),value.timeout_ms,'skip','skip',value.last_scheduled_at,value.next_run_at,null,null,now,now); else jsonSet(WORKFLOW_SCHEDULES_TABLE,value.id,dbRow(value)); return value }
export function updateWorkflowSchedule(id:string, patch:Partial<WorkflowScheduleRecord>): WorkflowScheduleRecord|null { const current=getWorkflowSchedule(id); if(!current)return null; const value={...current,...patch, id, concurrency_policy:'skip' as const,misfire_policy:'skip' as const, updated_at:Date.now()}; const db=getDb(); if(db) db.prepare(`UPDATE ${WORKFLOW_SCHEDULES_TABLE} SET schedule=?,timezone=?,enabled=?,input=?,start_node_ids_json=?,timeout_ms=?,last_scheduled_at=?,next_run_at=?,last_run_id=?,last_error=?,updated_at=? WHERE id=?`).run(value.schedule,value.timezone,value.enabled?1:0,value.input,JSON.stringify(value.start_node_ids),value.timeout_ms,value.last_scheduled_at,value.next_run_at,value.last_run_id,value.last_error,value.updated_at,id); else jsonSet(WORKFLOW_SCHEDULES_TABLE,id,dbRow(value)); return value }
export function deleteWorkflowSchedule(id:string):boolean { const db=getDb(); if(db)return db.prepare(`DELETE FROM ${WORKFLOW_SCHEDULES_TABLE} WHERE id=?`).run(id).changes>0; if(!jsonGet(WORKFLOW_SCHEDULES_TABLE,id))return false; jsonDelete(WORKFLOW_SCHEDULES_TABLE,id); return true }
export function deleteWorkflowSchedules(workflowId:string):void { for(const item of listWorkflowSchedules(workflowId)) deleteWorkflowSchedule(item.id) }
export function claimWorkflowScheduleTrigger(schedule:WorkflowScheduleRecord, scheduledAt:number): string|null { const identity=`${schedule.id}:${scheduledAt}`; const db=getDb(); try { if(db) db.prepare(`INSERT INTO ${WORKFLOW_SCHEDULE_TRIGGERS_TABLE} (identity,schedule_id,workflow_id,scheduled_at,created_at) VALUES (?,?,?,?,?)`).run(identity,schedule.id,schedule.workflow_id,scheduledAt,Date.now()); else { if(jsonGet(WORKFLOW_SCHEDULE_TRIGGERS_TABLE,identity)) return null; jsonSet(WORKFLOW_SCHEDULE_TRIGGERS_TABLE,identity,{identity,schedule_id:schedule.id,workflow_id:schedule.workflow_id,scheduled_at:scheduledAt,created_at:Date.now()}) }; return identity } catch { return null } }
export function createWorkflowScheduleEvent(input: Omit<WorkflowScheduleEventRecord,'id'|'created_at'>): WorkflowScheduleEventRecord { const value={...input,id:randomUUID(),created_at:Date.now()}; const db=getDb(); if(db) db.prepare(`INSERT INTO ${WORKFLOW_SCHEDULE_EVENTS_TABLE} (id,schedule_id,workflow_id,trigger_identity,scheduled_at,kind,run_id,error,created_at) VALUES (?,?,?,?,?,?,?,?,?)`).run(value.id,value.schedule_id,value.workflow_id,value.trigger_identity,value.scheduled_at,value.kind,value.run_id,value.error,value.created_at); else jsonSet(WORKFLOW_SCHEDULE_EVENTS_TABLE,value.id,value); return value }
export function listWorkflowScheduleEvents(scheduleId:string):WorkflowScheduleEventRecord[] { const db=getDb(); const values=db?(db.prepare(`SELECT * FROM ${WORKFLOW_SCHEDULE_EVENTS_TABLE} WHERE schedule_id=? ORDER BY created_at`).all(scheduleId) as any[]):Object.values(jsonGetAll(WORKFLOW_SCHEDULE_EVENTS_TABLE)).filter((v:any)=>v.schedule_id===scheduleId); return values as WorkflowScheduleEventRecord[] }
